# Generated by Django 5.1.1 on 2024-09-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_remove_bazaarlisting_created_at_bazaarlisting_name_and_more'),
        ('stocks', '0007_portfoliohistory_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaarlisting',
            name='stock',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
            preserve_default=False,
        ),
    ]
