# Generated by Django 5.1.1 on 2024-09-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_alter_bazaarlisting_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaarlisting',
            name='stock',
        ),
    ]
