# Generated by Django 5.1.1 on 2024-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0008_bazaarlisting_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
